#!/bin/sh

# Handle by mime types
case "$(file -Lb --mime-type -- "$1")" in
    text/* | */xml | application/json | application/x-ndjson) bat -p --theme ansi --terminal-width "$(($4-2))" -f "$1" ;;

    image/*)
        chafa --polite on --animate off "$1" -s "$2x$3"; exit ;;

    *) ;; # Go on to fall back
esac

# None of above exits, this is the fall back
echo '----- File Type Classification -----'
file --dereference --brief -- "$1"
