exec = gsettings set org.gnome.desktop.interface icon-theme 'Nordzy'
exec = gsettings set org.gnome.desktop.interface gtk-theme 'Nordic-Blue'
exec = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'

general {
    gaps_in = 3
    gaps_out = 8
    border_size = 2
    col.active_border = rgba(5A9ACAB4)
    col.inactive_border = rgba(2e3440d9)
    layout = dwindle
    resize_on_border = true
}

decoration {
    rounding = 7
    drop_shadow = false

    blur {
        enabled = yes
        size = 5
        passes = 3
        new_optimizations = on
        ignore_opacity = on
        xray = false
    }
}

