[window]
padding = { x = 15, y = 15 }

[font]
normal.family = "GoMonoNerdFontMono"
size = 8.0
offset.y = 2
glyph_offset.y = 1

# [colors.primary]
# background = "0x101010"
# foreground = "0xf7f7f7"
#
# [colors.cursor]
# text = "CellBackground"
# cursor = "CellForeground"
#
# [colors.vi_mode_cursor]
# text = "CellBackground"
# cursor = "CellForeground"
#
# [colors.normal]
# black = "0x272727"
# red = "0x974b46"
# green = "0x5f8787"
# yellow = "0xeecc6c"
# blue = "0x5f81a5"
# magenta = "0xb48ead"
# cyan = "0xd0dfee"
# white = "0xe3e3e3"
#
# [colors.bright]
# black = "0x464646"
# red = "0x974b46"
# green = "0x5f8787"
# yellow = "0xeecc6c"
# blue = "0x5f81a5"
# magenta = "0xb48ead"
# cyan = "0xd0dfee"
# white = "0xf7f7f7"

[colors.primary]
background = "#0e0e16"
foreground = "#d8d8d8"

[colors.cursor]
text = "#0e0e16"
cursor = "#d8d8d8"

[colors.selection]
text = "#d8d8d8"
background = "#33415c"

[colors.normal]
black = "#0e0e16"
red = "#ef8a90"
green = "#8ac490"
yellow = "#d1b77a"
blue = "#b0c0e0"
magenta = "#d58ca6"
cyan = "#70a8a8"
white = "#d8d8d8"

[colors.bright]
black = "#707c8c"
red = "#ef8a90"
green = "#8ac490"
yellow = "#d1b77a"
blue = "#b0c0e0"
magenta = "#d58ca6"
cyan = "#5fa6a6"
white = "#d8d8d8"
